version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: smalltalk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5555"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: