server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smalltalk
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

security:
  jwt:
    secret: your_jwt_secret_key
    expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    root: INFO
    com.thourie: DEBUG
